import test from 'node:test';
import assert from 'node:assert/strict';
import {existsSync,readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {Box3,Mesh} from 'three';
import {LDrawLoader} from 'three/addons/loaders/LDrawLoader.js';
import {LDrawConditionalLineMaterial} from 'three/addons/materials/LDrawConditionalLineMaterial.js';
// @ts-ignore native ESM catalog API
import {Library} from '../tools/catalog/library.mjs';
// @ts-ignore native ESM catalog API
import {packedModel,validateScene,IDENTITY} from '../tools/catalog/scene.mjs';
const dir=process.env.BRICKSMITH_LIBRARY??resolve('.cache/ldraw-official');const available=existsSync(resolve(dir,'.bricksmith-index.json'));const lib=(available?new Library(dir):null)!;
const options={skip:!available,timeout:30000};
test('official global catalog includes entire archive and independent categories beyond fourteen rectangles',options,()=>{const pin=JSON.parse(readFileSync(new URL('../tools/catalog/official-library.lock.json',import.meta.url),'utf8'));assert.equal(lib.manifest.archiveSha256,pin.archiveSha256);assert.equal(lib.manifest.counts.mainParts,24735);assert.equal(lib.manifest.counts.colors,322);for(const id of ['24309','43712','3544','6239','6233','54093','98100'])assert.ok(lib.part(id));assert.equal(lib.manifest.version,'2026-08');assert.equal(lib.manifest.colorConfigVersion,'2026-05-29');assert.ok(lib.files['p/box3#8p.dat']);});
test('specialized official meshes have curved/sloped vertices, real facets and round extents',options,()=>{const slope=lib.inspect('24309'),engine=lib.inspect('6233'),wing=lib.inspect('3544');assert.deepEqual(slope.bounds.size,[40,24,60]);assert.equal(engine.geometry.triangles,2184);assert.deepEqual(engine.bounds.size,[60,52,60]);assert.equal(wing.bounds.size[2],160);const g=lib.geometry('24309');const ys=new Set<number>();for(let i=1;i<g.points.length;i+=3)ys.add(g.points[i]);assert.ok(ys.size>10,'not a six-face rectangular proxy');});
test('independent Three LDrawLoader verifies rotated real meshes and native-LDU scene bounds',options,async()=>{const scene={schema:'bricksmith.scene.v1',name:'Independent specialty proof',units:'LDU',parts:[{id:'curve',part:'24309',color:15,position:[-80,0,0],rotation:[0,0,1,0,1,0,-1,0,0]},{id:'engine',part:'6233',color:72,position:[80,-40,50],rotation:[1,0,0,0,0,-1,0,1,0]},{id:'wing',part:'3544',color:4,position:[0,30,0],rotation:IDENTITY}]};const report=validateScene(scene,lib),pack=packedModel(scene,lib);const colors=lib.text('ldconfig.ldr').split(/\r?\n/).filter((s:string)=>s.startsWith('0 !COLOUR')).join('\n');const mpd=pack.model.replace('0 FILE model.ldr\n','0 FILE model.ldr\n'+colors+'\n');const loader=new LDrawLoader();loader.setConditionalLineMaterial(LDrawConditionalLineMaterial);loader.setFileMap(pack.fileMap);const group=await new Promise<import('three').Group>((done,reject)=>loader.parse(mpd,done,reject));group.updateMatrixWorld(true);const box=new Box3().setFromObject(group);for(const edge of ['min','max'] as const)for(let axis=0;axis<3;axis++)assert.ok(Math.abs(box[edge].getComponent(axis)-report.bounds[edge][axis])<.1);let triangles=0;group.traverse(o=>{if((o as Mesh).isMesh){const g=(o as Mesh).geometry;triangles+=(g.index?.count??g.attributes.position.count)/3;}});assert.ok(triangles>2000);assert.equal(report.structuralValidity,'unverified');});
test('actual upstream missing dependencies fail explicitly instead of silently blank meshes',options,()=>{for(const id of ['2374b','5241','6218741g'])assert.throws(()=>lib.inspect(id),{code:'DEPENDENCY_MISSING'});});
test('actual TEXMAP catalog entries remain searchable and render refusal is explicit',options,()=>{const candidate=lib.parts.find((p:any)=>p.kind==='main'&&p.texmap);assert.ok(candidate);const s={schema:'bricksmith.scene.v1',name:'Texture handling proof',units:'LDU',parts:[{id:'p',part:candidate.id,color:15,position:[0,0,0],rotation:IDENTITY}]};assert.throws(()=>packedModel(s,lib),{code:'UNSUPPORTED_TEXMAP'});});
