import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,mkdtempSync,writeFileSync,existsSync,rmSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {tmpdir} from 'node:os';
import {spawnSync} from 'node:child_process';
import {CAPS,ToolError,parseDesign,voxelize,compile,validate,catalog,type Design,type Shape} from '../tools/design.ts';
import {dimensions,inventory,toLDraw,toCSV,PART_BY_ID,type Brick,type Plan} from '../src/model.ts';
const root=resolve(import.meta.dirname,'..');
const box=(min:[number,number,number],size:[number,number,number]):Shape=>({type:'box',min,size});
const fixture=():Design=>({schema:'bricksmith.design.v1',name:'Uncatalogued test solid',description:'No routing by name.',bounds:{min:[0,0,0],size:[8,12,8]},shapes:[{op:'add',color:4,shape:box([0,0,0],[8,12,8])}]});
const throws=(fn:()=>unknown,code:string)=>assert.throws(fn,e=>e instanceof ToolError&&e.code===code);
const run=(args:string[],cwd=tmpdir())=>{const r=spawnSync(process.execPath,[join(root,'tools/bin.mjs'),...args],{cwd,encoding:'utf8',timeout:30000});assert.equal(r.signal,null,r.stderr);return {status:r.status,data:JSON.parse(r.stdout),stderr:r.stderr};};
function plan(bricks:Brick[]):Plan{return {version:1,name:'Failure fixture',description:'Intentional defects',source:'custom',bricks};}
const brick=(id:string,more:Partial<Brick>={}):Brick=>({id,part:'3001',color:4,x:0,y:0,z:0,rotation:0,...more});
// Independently expands actual catalog pieces, rather than trusting the compile report.
function expand(p:Plan){const map=new Map<string,number>();for(const b of p.bricks){const d=dimensions(b);assert.ok(PART_BY_ID[b.part]);for(let x=b.x;x<b.x+d.w;x++)for(let y=b.y;y<b.y+d.h;y++)for(let z=b.z;z<b.z+d.d;z++){const k=`${x},${y},${z}`;assert.ok(!map.has(k),`overlap ${k}`);map.set(k,b.color);}}return map;}

test('tool schema, catalog and help emit JSON from a different cwd',()=>{const c=run(['catalog']);assert.equal(c.status,0);assert.equal(c.data.parts.length,14);assert.equal(c.data.units.plateMm,3.2);assert.equal(run(['schema']).data.$id,'urn:bricksmith:design:v1');assert.equal(run(['schema','--kind','plan']).data.$id,'urn:bricksmith:plan:v1');assert.equal(run(['help']).data.exitCodes[3].includes('structural'),true);assert.equal(run(['schema','--kind','evil']).status,2);assert.equal(run(['catalog','--unknown','value']).status,2);});
test('strict schema rejects unknown fields, NaN, dimensions, colors, rotations and injection strings',()=>{const variants=[{...fixture(),model:'remote'}, {...fixture(),name:'line\nbreak'}, {...fixture(),bounds:{min:[0,0,0],size:[8.2,8,8]}}, {...fixture(),shapes:[{op:'add',color:4,shape:{type:'eval',code:'process.exit()'}}]}, {...fixture(),shapes:[{op:'add',color:NaN,shape:box([0,0,0],[1,1,1])}]}, {...fixture(),shapes:[{op:'add',color:4,shape:{type:'box',min:[0,0,0],size:[1,1,1],rotation:45}}]}, JSON.parse(JSON.stringify(fixture()).replace('"name":','"__proto__":{},"name":'))];for(const v of variants)assert.throws(()=>parseDesign(v));});
test('malformed primitives, CSG arrays and voxel overrides are rejected',()=>{for(const shape of [{type:'box',min:[0,0,0],size:[0,1,1]},{type:'ellipsoid',center:[0,0,0],radii:[1,Infinity,1]},{type:'cylinder',center:[0,0,0],radius:1,height:1,axis:'q'},{type:'union',children:[]},{type:'difference',children:[box([0,0,0],[1,1,1])]}])throws(()=>parseDesign({...fixture(),shapes:[{op:'add',color:4,shape}]}),'SCHEMA');const d=fixture();d.voxels=[{at:[0,0,0],color:1},{at:[0,0,0],color:2}];throws(()=>parseDesign(d),'SCHEMA');d.voxels=[{at:[8,0,0],color:1}];throws(()=>parseDesign(d),'BOUNDS');});
test('hard and caller-lowered resource caps fail before producing partial plans',()=>{throws(()=>parseDesign({...fixture(),bounds:{min:[0,0,0],size:[64,128,64]}}),'BUDGET');throws(()=>compile({...fixture(),limits:{maxVoxels:10}}),'BUDGET');throws(()=>compile({...fixture(),limits:{maxEvaluations:10}}),'BUDGET');throws(()=>compile({...fixture(),packing:{maxPieces:1}}),'BUDGET');throws(()=>parseDesign({...fixture(),packing:{maxPieces:5001}}),'SCHEMA');let shape:Shape=box([0,0,0],[1,1,1]);for(let i=0;i<17;i++)shape={type:'union',children:[shape,box([0,0,0],[1,1,1])]};throws(()=>parseDesign({...fixture(),shapes:[{op:'add',color:4,shape}]}),'BUDGET');const broad={type:'union',children:Array.from({length:32},()=>({type:'union',children:Array.from({length:4},()=>box([0,0,0],[1,1,1]))}))};throws(()=>parseDesign({...fixture(),shapes:[{op:'add',color:4,shape:broad}]}),'BUDGET');});
test('additive out-of-bounds shapes fail instead of silently cropping; explicit intersection works',()=>{const d=fixture();d.shapes[0].shape=box([-1,0,0],[9,4,8]);throws(()=>compile(d),'CLIPPED_SHAPE');d.shapes[0].shape={type:'intersection',children:[d.shapes[0].shape,box([0,0,0],[8,4,8])]};assert.equal(voxelize(d).cells.size,256);});
test('CSG ordered union, subtraction, intersection and paint implement exact center semantics',()=>{const d=fixture();d.bounds.size=[4,4,4];d.shapes=[{op:'add',color:4,shape:{type:'union',children:[box([0,0,0],[2,4,4]),box([2,0,0],[2,4,4])]}},{op:'subtract',shape:box([1,1,1],[2,3,2])},{op:'paint',color:1,shape:box([0,0,0],[4,4,2])}];const {cells}=voxelize(d);assert.equal(cells.size,64-12);assert.equal(cells.has('1,2,1'),false);assert.equal(cells.get('0,0,0'),1);assert.equal(cells.get('0,0,3'),4);assert.deepEqual(expand(compile(d).plan),cells);});
test('difference uses first child minus all following children, with no implicit fill',()=>{const d=fixture();d.shapes[0].shape={type:'difference',children:[box([0,0,0],[8,12,8]),box([1,1,1],[2,11,2]),box([5,1,5],[2,11,2])]};const {cells}=voxelize(d);assert.equal(cells.size,768-88);assert.equal(cells.has('1,1,1'),false);assert.equal(cells.has('5,1,5'),false);assert.equal(cells.has('1,0,1'),true);});
test('ellipsoid and all cylinder axes are sampled volumetrically rather than as heightmaps',()=>{for(const axis of ['x','y','z'] as const){const d=fixture();d.shapes=[{op:'add',color:4,shape:{type:'cylinder',center:[4,4,4],radius:2,height:4,axis}}];const {cells}=voxelize(d);let count=0;const a=['x','y','z'].indexOf(axis);for(let x=0;x<8;x++)for(let y=0;y<12;y++)for(let z=0;z<8;z++){const p=[x+.5,y+.5,z+.5],inside=Math.abs(p[a]-4)<2&&p.reduce((s,v,i)=>s+(i===a?0:(v-4)**2),0)<=4;assert.equal(cells.has(`${x},${y},${z}`),inside);if(inside)count++;}assert.equal(cells.size,count);assert.deepEqual(expand(compile(d).plan),cells);}const d=fixture();d.shapes=[{op:'add',color:15,shape:{type:'ellipsoid',center:[4,6,4],radii:[3,5,3]}}];const {cells}=voxelize(d);assert.ok(cells.has('3,5,3'));assert.ok(!cells.has('1,1,1'));assert.ok(!cells.has('0,0,0'));assert.deepEqual(expand(compile(d).plan),cells);});
test('explicit voxels can define genuinely new disconnected objects and never get auto-supports',()=>{const d=fixture();d.shapes=[];d.voxels=[{at:[1,2,3],color:14},{at:[4,5,6],color:1}];const {plan,report}=compile(d);assert.equal(plan.bricks.length,2);assert.equal(report.valid,false);assert.equal(report.summary.unsupported,2);assert.equal(report.summary.components,2);assert.equal(report.fidelity?.extra,0);assert.deepEqual(expand(plan),voxelize(d).cells);});
test('voxel overrides recolor/add/delete last; paint cannot create new matter',()=>{const d=fixture();d.shapes=[{op:'paint',color:1,shape:box([0,0,0],[8,12,8])}];throws(()=>compile(d),'EMPTY');d.shapes[0].op='add';d.voxels=[{at:[0,0,0],color:null},{at:[1,0,0],color:14}];assert.equal(voxelize(d).cells.get('1,0,0'),14);assert.equal(voxelize(d).cells.has('0,0,0'),false);});
test('packing is deterministic, uses valid parts and alternates feasible seams without changing color cells',()=>{const d=fixture(),a=compile(d),b=compile(d);assert.deepEqual(a,b);assert.equal(a.report.valid,true);assert.deepEqual(expand(a.plan),voxelize(d).cells);assert.ok(a.plan.bricks.some(b=>dimensions(b).h===3));assert.ok(new Set(a.plan.bricks.map(b=>b.rotation)).size>1);d.packing={mode:'plates'};assert.ok(compile(d).plan.bricks.every(b=>dimensions(b).h===1));});
test('varied deterministic random voxel grids preserve every color and empty cell',()=>{let seed=42;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/2**32;};for(let j=0;j<18;j++){const d=fixture();d.bounds={min:[-3,0,-3],size:[6,7,6]};d.shapes=[];d.voxels=[];for(let y=0;y<7;y++)for(let z=-3;z<3;z++)for(let x=-3;x<3;x++)if(rand()>.4)d.voxels.push({at:[x,y,z],color:[1,4,14][Math.floor(rand()*3)]});const {plan,report}=compile(d);assert.equal(report.fidelity?.exact,true);assert.deepEqual(expand(plan),voxelize(d).cells);}});
test('validation gives piece-specific collision, unsupported, partial-support and component actions',()=>{const p=plan([brick('base'),brick('overlap'),brick('partial',{x:3,y:3}),brick('floating',{x:12,y:8}),brick('side',{x:6})]);const r=validate(p);assert.equal(r.valid,false);assert.ok(r.issues.find(i=>i.code==='COLLISION')?.pieceIds.includes('overlap'));assert.ok(r.issues.find(i=>i.code==='UNSUPPORTED')?.pieceIds.includes('floating'));assert.ok(r.issues.some(i=>i.code==='PARTIAL_SUPPORT'));assert.ok(r.issues.some(i=>i.code==='DISCONNECTED'));for(const issue of r.issues)assert.ok(issue.action.length>10);});
test('pathological overlaps retain a hard truncated failure, never claim a green report',()=>{const r=validate(plan(Array.from({length:80},(_,i)=>brick('b'+i))));assert.equal(r.summary.collisions,1000);assert.equal(r.summary.truncated,true);assert.equal(r.valid,false);assert.ok(r.issues.some(i=>i.code==='DIAGNOSTICS_TRUNCATED'));});
test('fidelity reports missing, extra and wrong-color cells with coordinates',()=>{const d=fixture(),p=compile(d).plan;p.bricks[0].color=1;p.bricks.pop();p.bricks.push(brick('extra',{x:50}));const r=validate(p,d);assert.equal(r.fidelity?.exact,false);assert.ok(r.fidelity!.missing>0);assert.ok(r.fidelity!.extra>0);assert.ok(r.fidelity!.wrongColor>0);assert.ok(r.fidelity!.examples.length>0);});
test('penguin revision keeps original defect evidence and repaired source passes limited checks',()=>{const original=JSON.parse(readFileSync(join(root,'examples/agent/penguin-v1.design.json'),'utf8'));const repaired=JSON.parse(readFileSync(join(root,'examples/agent/penguin.design.json'),'utf8'));const first=compile(original),last=compile(repaired);assert.equal(first.report.valid,false);assert.equal(first.report.fidelity?.exact,true);assert.equal(last.report.valid,true);assert.equal(last.report.summary.components,1);assert.equal(last.report.summary.unsupported,0);assert.equal(last.report.fidelity?.exact,true);assert.ok(last.report.fidelity!.targetVoxels>first.report.fidelity!.targetVoxels);assert.deepEqual(expand(last.plan),voxelize(repaired).cells);});
test('CLI compile/validate/export from unrelated cwd preserve inventory, LDraw placements and notebook IDs',()=>{const dir=mkdtempSync(join(tmpdir(),'bricksmith-cli-test-'));try{const source=join(dir,'design.json');writeFileSync(source,JSON.stringify(fixture()));const out=join(dir,'compiled');assert.equal(run(['compile','--design',source,'--out',out]).status,0);const p=JSON.parse(readFileSync(join(out,'plan.json'),'utf8'));assert.equal(run(['validate','--plan',join(out,'plan.json'),'--design',source]).status,0);const exported=join(dir,'exported');const r=run(['export','--plan',join(out,'plan.json'),'--design',source,'--out',exported]);assert.equal(r.status,0);assert.equal(inventory(p).reduce((s,r)=>s+r.quantity,0),p.bricks.length);assert.equal(readFileSync(join(exported,'model.ldr'),'utf8'),toLDraw(p));assert.equal(readFileSync(join(exported,'model.ldr'),'utf8').split('\r\n').filter(l=>l.startsWith('1 ')).length,p.bricks.length);assert.equal(readFileSync(join(exported,'inventory.csv'),'utf8'),toCSV(p));const html=readFileSync(join(exported,'instructions.html'),'utf8');for(const b of p.bricks)assert.ok(html.includes(' / '+b.id+'</td>'));assert.equal(run(['export','--plan',join(out,'plan.json'),'--out',out]).status,2);}finally{rmSync(dir,{recursive:true,force:true});}});
test('CLI malformed/oversized input and piece budget return structured exit 2 without artifacts',()=>{const dir=mkdtempSync(join(tmpdir(),'bricksmith-bad-test-'));try{const f=join(dir,'bad.json'),out=join(dir,'out');writeFileSync(f,'{oops');assert.equal(run(['compile','--design',f,'--out',out]).data.error.code,'JSON');writeFileSync(f,' '.repeat(CAPS.inputBytes+1));const big=run(['compile','--design',f,'--out',out]);assert.equal(big.status,2);assert.equal(big.data.error.code,'INPUT_BUDGET');writeFileSync(f,JSON.stringify({...fixture(),packing:{maxPieces:1}}));assert.equal(run(['compile','--design',f,'--out',out]).status,2);assert.equal(existsSync(out),false);assert.equal(run(['render','--plan',f,'--out',out,'--size','99999']).status,2);}finally{rmSync(dir,{recursive:true,force:true});}});
test('CLI structural defects exit 3 with a repairable plan/report rather than suppressing output',()=>{const dir=mkdtempSync(join(tmpdir(),'bricksmith-defect-test-'));try{const d=fixture();d.shapes=[];d.voxels=[{at:[2,5,2],color:14}];const f=join(dir,'input.json'),out=join(dir,'out');writeFileSync(f,JSON.stringify(d));const r=run(['compile','--design',f,'--out',out]);assert.equal(r.status,3);assert.equal(r.data.fidelity.exact,true);assert.ok(existsSync(join(out,'plan.json')));assert.equal(run(['validate','--plan',join(out,'plan.json')]).status,3);}finally{rmSync(dir,{recursive:true,force:true});}});
test('maximum disconnected plans mark issue-list truncation explicitly',()=>{const p=plan(Array.from({length:5000},(_,i)=>brick('solo'+i,{part:'3024',x:(i%128)-64,z:Math.floor(i/128)-32,y:5})));const r=validate(p);assert.equal(r.summary.unsupported,5000);assert.equal(r.summary.components,5000);assert.equal(r.summary.issuesTruncated,true);assert.equal(r.summary.truncated,true);assert.equal(r.issues.length,CAPS.issues);assert.equal(r.issues.at(-1)?.code,'ISSUES_TRUNCATED');assert.equal(r.valid,false);});
test('tool plan input rejects unknown fields and reports invalid piece index',()=>{throws(()=>validate({...plan([brick('a')]),execute:'unsafe'}),'SCHEMA');assert.throws(()=>validate(plan([brick('a',{part:'not-a-part'})])),e=>e instanceof ToolError&&e.path==='$.bricks[0]');});
