import {chromium,expect} from '@playwright/test';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {resolve} from 'node:path';
const base=process.env.BRICKSMITH_URL||'http://127.0.0.1:4173';
const out=resolve(process.env.BRICKSMITH_TEST_OUT||'artifacts');await mkdir(out,{recursive:true});await mkdir(resolve(out,'downloads'),{recursive:true});
const launch={headless:true,args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']};
if(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE)launch.executablePath=process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE;
else if(existsSync('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'))launch.executablePath='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const browser=await chromium.launch(launch);const context=await browser.newContext({viewport:{width:1440,height:1080},deviceScaleFactor:1,acceptDownloads:true});
const errors=[],external=[],checks=[];let page;
context.on('page',p=>{p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});});
await context.route('**/*',route=>{const url=route.request().url();if(url.startsWith(base)||url.startsWith('blob:')||url.startsWith('data:'))return route.continue();external.push(url);return route.abort();});
async function check(name,fn){await fn();checks.push(name);console.log('PASS '+name);}
async function downloaded(button,filename){const promise=page.waitForEvent('download');await page.locator(button).click();const download=await promise;const path=resolve(out,'downloads',filename);await download.saveAs(path);return path;}
try{
 page=await context.newPage();await page.goto(base,{waitUntil:'networkidle'});await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');
 await check('default model and WebGL studded geometry load',async()=>{await expect(page.locator('#model-name')).toHaveText('Little hillside cottage');await expect(page.locator('#viewer canvas')).toHaveAttribute('data-bricks','213');const studs=Number(await page.locator('#viewer canvas').getAttribute('data-studs'));expect(studs).toBeGreaterThan(213);await expect(page.locator('#webgl-error')).toBeHidden();});
 await page.waitForTimeout(500);await page.screenshot({path:resolve(out,'desktop.png'),fullPage:true});await page.locator('.viewport-wrap').screenshot({path:resolve(out,'cottage-viewer.png')});
 await check('assembly slider changes actual visible instance count and layer map',async()=>{await page.locator('#step').fill('0');await expect(page.locator('#viewer canvas')).toHaveAttribute('data-bricks','32');await expect(page.locator('#step-title')).toContainText('Step 1 of 16');await expect(page.locator('#layer-map svg')).toHaveAttribute('aria-label',/step 1/);await page.locator('#next').click();expect(Number(await page.locator('#viewer canvas').getAttribute('data-bricks'))).toBeGreaterThan(32);await page.locator('#all-steps').click();await expect(page.locator('#viewer canvas')).toHaveAttribute('data-bricks','213');});
 await check('camera fit/top/orbit/explode and brick picking are interactive',async()=>{await page.locator('#explode').click();await expect(page.locator('#explode')).toHaveAttribute('aria-pressed','true');await page.locator('#explode').click();await page.locator('#spin').click();await expect(page.locator('#spin')).toHaveAttribute('aria-pressed','true');await page.locator('#spin').click();await page.locator('#top').click();await page.locator('#fit').click();const canvas=page.locator('#viewer canvas');await canvas.focus();await page.keyboard.press('+');await page.keyboard.press('Home');const box=await canvas.boundingBox();await page.mouse.click(box.x+box.width*.5,box.y+box.height*.5);await expect(page.locator('#selection')).toBeVisible();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.6,box.y+box.height*.57,{steps:8});await page.mouse.up();await page.locator('#fit').click();});
 await check('inventory totals equal complete model, even during an early assembly step',async()=>{await page.locator('#step').fill('0');await page.locator('#inventory-tab').click();const quantities=await page.locator('#inventory-body td.numeric').allTextContents();expect(quantities.reduce((n,s)=>n+Number(s),0)).toBe(213);await page.locator('#assembly-tab').click();await page.locator('#all-steps').click();});
 await check('unsupported prompts fail honestly and preserve previous build',async()=>{await page.locator('#prompt').fill('a dragon flying over a spaceship');await page.locator('#generate').click();await expect(page.locator('#status')).toContainText('not supported');await expect(page.locator('#piece-count')).toHaveText('213');});
 await check('budget failures are atomic and no partial plan replaces the model',async()=>{await page.locator('#prompt').fill('a cottage');await page.locator('#budget').fill('20');await page.locator('#generate').click();await expect(page.locator('#status')).toContainText('No partial model');await expect(page.locator('#piece-count')).toHaveText('213');await page.locator('#budget').fill('1200');});
 await check('size/height and palette controls generate a distinct constrained model',async()=>{await page.locator('#prompt').fill('a blue tower size 12 height 4');await page.locator('#palette').selectOption('mono');await page.locator('#generate').click();await expect(page.locator('#model-name')).toHaveText('The watchtower');await expect(page.locator('#size')).toHaveValue('12');await expect(page.locator('#height')).toHaveValue('4');await expect(page.locator('#footprint')).toHaveText('12 × 12');await expect(page.locator('#model-description')).toContainText('mono');});
 await check('image file becomes a genuine aspect-preserved quantized mosaic',async()=>{await page.locator('#image-tab').click();await page.locator('#size').fill('24');await page.locator('#height').fill('6');await page.locator('#palette').selectOption('classic');await page.locator('#image-file').setInputFiles(resolve('samples/source-landscape.png'));await expect(page.locator('#model-name')).toHaveText('Image plate mosaic');await expect(page.locator('#footprint')).toHaveText('24 × 16');await expect(page.locator('#piece-count')).toHaveText('182');await expect(page.locator('#step-count')).toHaveText('3');await expect(page.locator('#image-preview')).toBeVisible();});
 await page.locator('#top').click();await page.waitForTimeout(400);await check('rendered top-view pixel orientation matches source and instruction map',async()=>{const colors=await page.locator('#viewer canvas').evaluate(async canvas=>{const image=new Image();image.src=canvas.toDataURL('image/png');await image.decode();const copy=document.createElement('canvas');copy.width=canvas.width;copy.height=canvas.height;const ctx=copy.getContext('2d');ctx.drawImage(image,0,0);return [.25,.75].map(y=>Array.from(ctx.getImageData(Math.floor(copy.width*.5),Math.floor(copy.height*y),1,1).data));});expect(colors[0][2]).toBeGreaterThan(colors[0][1]*1.15);expect(colors[1][1]).toBeGreaterThan(colors[1][2]*1.15);});await page.screenshot({path:resolve(out,'image-mosaic.png'),fullPage:true});await page.locator('#fit').click();
 await check('brightness relief changes real geometry and is honestly labeled',async()=>{await page.locator('input[value="relief"]').check();await page.locator('#generate').click();await expect(page.locator('#model-name')).toHaveText('Image brightness relief');await expect(page.locator('#model-description')).toContainText('NOT inferred 3D shape');await expect(page.locator('#piece-count')).toHaveText('332');await expect(page.locator('#step-count')).toHaveText('7');});
 await page.waitForTimeout(300);await page.screenshot({path:resolve(out,'image-relief.png'),fullPage:true});
 await check('custom JSON import validates before loading and reports collisions',async()=>{await page.locator('#custom-open').click();await page.locator('#json-text').fill('{"version":7}');await page.locator('#import-json').click();await expect(page.locator('#json-status')).toContainText('Unsupported plan version');const b={id:'a',part:'3001',color:4,x:0,y:0,z:0,rotation:0};await page.locator('#json-text').fill(JSON.stringify({version:1,name:'Collision fixture',source:'custom',description:'Intentional overlapping bodies.',bricks:[b,{...b,id:'b'}]}));await page.locator('#import-json').click();await expect(page.locator('#model-name')).toHaveText('Collision fixture');await page.locator('#checks-tab').click();await expect(page.locator('#checks-grid>div').first()).toContainText('1Body overlaps');});
 await check('JSON file import restores the exact sample plan',async()=>{await page.locator('#custom-open').click();await page.locator('#json-file').setInputFiles(resolve('samples/cottage.json'));await expect(page.locator('#json-status')).toContainText('File read locally');await page.locator('#import-json').click();await expect(page.locator('#piece-count')).toHaveText('213');await page.locator('#assembly-tab').click();});
 await check('all five export downloads contain actual data, full-model regardless of step',async()=>{await page.locator('#step').fill('0');await page.locator('#export-open').click();const ldr=await downloaded('#download-ldr','cottage.ldr'),csv=await downloaded('#download-csv','cottage.csv'),json=await downloaded('#download-json','cottage.json'),html=await downloaded('#download-html','cottage.html'),png=await downloaded('#download-png','cottage.png');expect((await readFile(ldr,'utf8')).split('\r\n').filter(l=>l.startsWith('1 ')).length).toBe(213);expect(await readFile(csv,'utf8')).toBe(await readFile('samples/cottage.csv','utf8'));expect(JSON.parse(await readFile(json,'utf8')).bricks.length).toBe(213);expect(await readFile(html,'utf8')).toContain('Assembly 16 / 16');expect((await readFile(png)).subarray(1,4).toString()).toBe('PNG');await page.locator('[data-close="export-dialog"]').click();await page.locator('#all-steps').click();});
 await check('printable notebook opens, renders all step maps, and produces a PDF',async()=>{const popup=context.waitForEvent('page');await page.locator('#instructions').click();const book=await popup;await book.waitForLoadState();await expect(book.locator('.step')).toHaveCount(16);await expect(book.locator('svg')).toHaveCount(16);await book.emulateMedia({media:'print'});await expect(book.locator('.toolbar')).toBeHidden();await book.pdf({path:resolve(out,'cottage-instructions.pdf'),format:'A4',printBackground:true});await book.close();});
 await check('keyboard tabs switch input and details accessibly',async()=>{await page.locator('#text-tab').click();await page.locator('#text-tab').focus();await page.keyboard.press('ArrowRight');await expect(page.locator('#image-tab')).toBeFocused();await expect(page.locator('#image-tab')).toHaveAttribute('aria-selected','true');await page.keyboard.press('Home');await expect(page.locator('#text-tab')).toBeFocused();await page.locator('#assembly-tab').focus();await page.keyboard.press('ArrowRight');await expect(page.locator('#inventory-tab')).toHaveAttribute('aria-selected','true');await page.keyboard.press('Home');});
 await check('runtime still generates with network offline after assets load',async()=>{await context.setOffline(true);await page.locator('#prompt').fill('a tan pyramid');await page.locator('#generate').click();await expect(page.locator('#model-name')).toHaveText('Stepped desert pyramid');await context.setOffline(false);});
 await page.locator('#size').fill('16');await page.locator('#height').fill('8');await page.locator('[data-prompt="A tan cottage with a red roof"]').click();await page.locator('#assembly-tab').click();
 await check('mobile 390px layout has no horizontal overflow and keeps usable 3D view',async()=>{await page.setViewportSize({width:390,height:844});await page.waitForTimeout(400);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('#fit').click();await page.locator('.bench-heading').scrollIntoViewIfNeeded();await page.screenshot({path:resolve(out,'mobile.png'),fullPage:true});await page.locator('#export-open').click();expect(await page.locator('#export-dialog').evaluate(el=>el.getBoundingClientRect().width)).toBeLessThan(390);await page.keyboard.press('Escape');});
 await check('WebGL failure degrades to usable assembly maps and exports',async()=>{const fallback=await context.newPage();await fallback.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){if(String(type).includes('webgl'))return null;return original.call(this,type,...args);};});await fallback.goto(base);await expect(fallback.locator('#webgl-error')).toBeVisible();await expect(fallback.locator('#layer-map svg')).toBeVisible();await fallback.locator('[data-prompt="A gray tower"]').click();await expect(fallback.locator('#model-name')).toHaveText('The watchtower');await expect(fallback.locator('#download-png')).toBeDisabled();await fallback.close();});
 // Three logs its expected WebGL initialization failure in the deliberately disabled context.
 const unexpected=errors.filter(e=>!e.includes('Error creating WebGL context.'));
 await check('no unexpected browser errors or external requests',async()=>{expect(unexpected).toEqual([]);expect(external).toEqual([]);});
 const report={status:'passed',checks:checks.length,names:checks,browser:browser.version(),base,unexpectedErrors:unexpected,externalRequests:external,createdAt:new Date().toISOString()};await writeFile(resolve(out,'browser-report.json'),JSON.stringify(report,null,2)+'\n');console.log(`${checks.length} browser smoke checks passed.`);
}catch(error){await page?.screenshot({path:resolve(out,'failure.png'),fullPage:true}).catch(()=>{});await writeFile(resolve(out,'browser-report.json'),JSON.stringify({status:'failed',checks,names:checks,error:String(error),errors,external},null,2));throw error;}finally{await browser.close();}
