import {open,readFile,mkdir,writeFile,rename,unlink} from 'node:fs/promises';
import {resolve,join,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {CAPS,ToolError,catalog,compile,validate,parsePlan} from './design.ts';
import {toLDraw,toCSV,toJSON} from '../src/model.ts';
import {instructionHTML} from '../src/instructions.ts';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
export async function readJSON(path:string){const handle=await open(resolve(path),'r');try{const stat=await handle.stat();if(!stat.isFile())throw new ToolError('INPUT_TYPE','Input must be a regular JSON file',path);if(stat.size>CAPS.inputBytes)throw new ToolError('INPUT_BUDGET','Input exceeds 4 MB',path);const data=Buffer.alloc(CAPS.inputBytes+1);let total=0;while(total<data.length){const {bytesRead}=await handle.read(data,total,data.length-total,null);if(!bytesRead)break;total+=bytesRead;}if(total>CAPS.inputBytes)throw new ToolError('INPUT_BUDGET','Input exceeds 4 MB',path);try{return JSON.parse(data.subarray(0,total).toString('utf8'));}catch{throw new ToolError('JSON','Invalid JSON',path);}}finally{await handle.close();}}
async function put(path:string,data:string){await mkdir(dirname(path),{recursive:true});const temp=path+`.${process.pid}.tmp`;try{await writeFile(temp,data,{flag:'wx'});await rename(temp,path);}finally{await unlink(temp).catch(()=>{});}}
const json=(v:unknown)=>JSON.stringify(v,null,2)+'\n';
import {catalogContract} from './catalog/cli.mjs';
const contract={fullCatalog:catalogContract,tool:'bricksmith',version:'0.3.0',commands:{schema:'schema [--kind design|plan]',catalog:'catalog',compile:'compile --design design.json --out output-directory',validate:'validate --plan plan.json [--design design.json] [--out report.json]',render:'render --plan plan.json --out views-directory [--size 900] [--browser /path/to/chromium]',export:'export --plan plan.json --out output-directory [--design design.json]'},exitCodes:{0:'Command complete; compile/validate/export have no report errors (warnings may remain); render does not certify structure',2:'Invalid schema/arguments or resource budget',3:'Plan written/checked but structural or fidelity errors exist; inspect report',4:'Filesystem/browser/runtime dependency failure',5:'Internal invariant failure'},noAI:'The calling host agent is the designer. No AI calls. Legacy commands are offline; only the explicit full-catalog library install command may download the official archive.'};
async function main(){const [command='help',...argv]=process.argv.slice(2),opts:Record<string,string>={};const allowed:Record<string,string[]>={help:[],schema:['kind'],catalog:[],compile:['design','out'],validate:['plan','design','out'],render:['plan','out','size','browser'],export:['plan','design','out']};if(!Object.hasOwn(allowed,command))throw new ToolError('ARGUMENT','Unknown command; use help');for(let i=0;i<argv.length;i+=2){const key=argv[i].slice(2);if(!argv[i].startsWith('--')||!allowed[command].includes(key)||opts[key]!==undefined||!argv[i+1]||argv[i+1].startsWith('--'))throw new ToolError('ARGUMENT',`Invalid/duplicate option ${argv[i]}`);opts[key]=argv[i+1];}
 const need=(key:string)=>{if(!opts[key])throw new ToolError('ARGUMENT',`Missing --${key}`);return resolve(opts[key]);};
 const safeOutputs=(files:string[])=>{const inputs=['plan','design'].filter(k=>opts[k]).map(k=>resolve(opts[k]));if(files.some(p=>inputs.includes(resolve(p))))throw new ToolError('ARGUMENT','Output would overwrite input. Use a separate output directory.');};
 if(command==='help')return contract;
 if(command==='catalog')return catalog();
 if(command==='schema'){const kind=opts.kind??'design';if(!['design','plan'].includes(kind))throw new ToolError('ARGUMENT','kind must be design or plan');return JSON.parse(await readFile(join(root,'tools/schema',kind+'.schema.json'),'utf8'));}
 if(command==='compile'){const input=need('design'),out=need('out'),{plan,report}=compile(await readJSON(input));const files={plan:join(out,'plan.json'),report:join(out,'report.json')};safeOutputs(Object.values(files));await put(files.plan,toJSON(plan));await put(files.report,json(report));process.exitCode=report.valid?0:3;return {ok:report.valid,command,files,pieces:report.pieces,summary:report.summary,fidelity:report.fidelity};}
 const input=need('plan');const plan=parsePlan(await readJSON(input));
 if(command==='render'){const out=need('out'),size=Number(opts.size??900);if(!Number.isInteger(size)||size<256||size>1600)throw new ToolError('ARGUMENT','size must be an integer 256–1600');safeOutputs(['front','back','left','right','top','iso'].map(n=>join(out,n+'.png')).concat(join(out,'render.json')));const {render}=await import('./render.ts');return {ok:true,command,...await render(plan,out,size,opts.browser)};}
 const report=validate(plan,opts.design?await readJSON(opts.design):undefined);process.exitCode=report.valid?0:3;
 if(command==='validate'){if(opts.out){const out=resolve(opts.out);safeOutputs([out]);await put(out,json(report));}return report;}
 const out=need('out'),files={plan:join(out,'plan.json'),report:join(out,'report.json'),ldraw:join(out,'model.ldr'),inventory:join(out,'inventory.csv'),instructions:join(out,'instructions.html')};safeOutputs(Object.values(files));const html=instructionHTML(plan).replace('Start base pieces on a flat surface; generated designs include a second backing layer intended to tie them together; check the connected-group diagnostic. Custom plans may not include backing.','Start base pieces on a flat surface. This notebook includes only the listed parts and geometry; no backing layer, foundation or support is implied. Check the connected-group diagnostic.');if(Buffer.byteLength(html)>32_000_000)throw new ToolError('OUTPUT_BUDGET','Instructions exceed 32 MB; reduce footprint/pieces/elevations.');
 await put(files.plan,toJSON(plan));await put(files.report,json(report));await put(files.ldraw,toLDraw(plan));await put(files.inventory,toCSV(plan));await put(files.instructions,html);return {ok:report.valid,command,files,pieces:report.pieces,summary:report.summary};
}
main().then(result=>process.stdout.write(json(result))).catch(error=>{process.exitCode=error instanceof ToolError?error.exitCode:4;process.stdout.write(json({ok:false,error:{code:error instanceof ToolError?error.code:'RUNTIME',message:error.message,path:error instanceof ToolError?error.path:undefined,details:error instanceof ToolError?error.details:undefined},exitCode:process.exitCode}));});
