import './style.css';
import {BrickViewer} from './viewer';
import {procedural, imagePlan, parsePrompt} from './generate';
import {DEFAULTS, PALETTES, COLOR_BY_CODE, PART_BY_ID, bounds, layers, ordered, inventory, diagnose, validatePlan, enforceBudget, toCSV, toJSON, toLDraw, escapeHTML as esc, type Plan, type Options} from './model';
import {layerSVG, instructionHTML} from './instructions';

const $ = <T extends HTMLElement = HTMLElement>(id:string) => document.getElementById(id) as T;
document.querySelector('#app')!.innerHTML = `
<header class="topbar"><a class="brand" href="/" aria-label="Bricksmith home"><img src="/brick.svg" alt=""><span>bricksmith<span class="brand-dot">.</span></span></a><div class="header-center">THE LOCAL BRICK WORKSHOP <span> / </span> 01</div><div class="local-badge"><i></i> On-device. By design.</div></header>
<main class="workspace">
<aside class="creation"><div class="eyebrow">FROM A LITTLE IDEA</div><h1>Make it<br><em>piece by piece.</em></h1><p class="intro">A small workshop for things you can hold. No AI magic. Just real, editable brick plans.</p>
<div class="input-tabs" role="tablist" aria-label="Design input"><button id="text-tab" role="tab" aria-selected="true" aria-controls="text-panel">Aa <span>Describe</span></button><button id="image-tab" role="tab" aria-selected="false" aria-controls="image-panel" tabindex="-1">▧ <span>Use an image</span></button></div>
<section id="text-panel" role="tabpanel" aria-labelledby="text-tab"><label class="field-label" for="prompt">Your starting point</label><textarea id="prompt" maxlength="500" rows="3" spellcheck="false">A tan cottage with a red roof</textarea><div class="suggestions"><button data-prompt="A tan cottage with a red roof">Cottage</button><button data-prompt="A gray tower">Tower</button><button data-prompt="A tan pyramid">Pyramid</button></div><p class="hint">Local procedural families only: cottage, tower, pyramid. Colors, size and height supported. <button id="syntax" class="text-link">Prompt guide</button></p></section>
<section id="image-panel" role="tabpanel" aria-labelledby="image-tab" hidden><label id="drop-zone" class="drop-zone" for="image-file"><img id="image-preview" alt="Selected source image" hidden><span id="upload-label"><b>＋ Add your image</b><small>or drop it here · PNG, JPG, WebP · ≤20 MB</small></span><input id="image-file" type="file" accept="image/png,image/jpeg,image/webp"></label><fieldset class="mode-picker"><legend>Image conversion</legend><label><input type="radio" name="image-mode" value="mosaic" checked> Flat mosaic</label><label><input type="radio" name="image-mode" value="relief"> Brightness relief</label></fieldset><p class="hint">A quantized plate picture, not photo-to-3D. Relief stacks brighter pixels higher. Aspect ratio is preserved; transparent pixels become white.</p></section>
<div class="settings"><div class="setting-heading"><span class="field-label">Make it yours</span><span class="micro">01 / PARAMETERS</span></div><label class="range-label" for="size">Base / image size <span><output id="size-value">16</output> studs</span></label><input id="size" type="range" min="8" max="40" step="1" value="16"><div class="range-ends"><span>Small & simple</span><span>More detail</span></div><label class="range-label" for="height">Body / relief height <span><output id="height-value">8</output> <span id="height-unit">courses</span></span></label><input id="height" type="range" min="3" max="20" step="1" value="8"><p id="height-hint" class="hint compact">Body courses; base and cottage roof are additional.</p><div class="two-fields"><label for="palette">Palette<select id="palette"><option value="classic">Classic · 12 colors</option><option value="earth">Earth · 7 colors</option><option value="mono">Monochrome · 4 colors</option></select></label><label for="budget">Piece budget<input id="budget" type="number" min="20" max="5000" step="1" value="1200"></label></div><div id="palette-swatches" class="palette-swatches" aria-label="Selected palette"></div></div>
<button id="generate" class="primary generate">Build my model <span>→</span></button><div id="status" class="status" role="status" aria-live="polite">Demo loaded. Make it your own.</div><button id="custom-open" class="custom-link">{ } Import / paste a custom JSON plan <span>↗</span></button><div class="private-note"><span>◉</span><p><b>Your ideas stay here.</b><br>Images and plans are processed in your browser. No accounts, APIs or uploads.</p></div></aside>
<section class="bench" aria-label="Model workbench"><div class="bench-heading"><div><p class="eyebrow">ON THE WORKBENCH</p><h2 id="model-name"></h2></div><span class="source-tag" id="source-tag">PROCEDURAL</span></div>
<div class="viewport-wrap"><div class="viewer-toolbar" aria-label="3D viewer controls"><button id="fit" title="Reset camera (Home)">↙ <span>Fit</span></button><button id="top" title="View from above">▤ <span>Top</span></button><button id="explode" aria-pressed="false" title="Separate layers for inspection">☷ <span>Explode</span></button><button id="spin" aria-pressed="false" title="Auto-rotate model">⟳ <span>Orbit</span></button></div><div id="viewer"></div><div id="webgl-error" class="webgl-error" hidden></div><div class="model-corner"><span class="live-dot"></span> <span id="visible-count"></span> <span class="muted">PIECES ON VIEW</span></div><div class="orbit-hint">DRAG TO ORBIT <span>·</span> SCROLL TO ZOOM <span>·</span> CLICK A BRICK</div><div id="selection" class="selection" role="status" hidden></div></div>
<div class="stats"><div><strong id="piece-count"></strong><span>pieces</span></div><div><strong id="color-count"></strong><span>colors</span></div><div><strong id="footprint"></strong><span>stud footprint</span></div><div><strong id="step-count"></strong><span>assembly steps</span></div></div>
<div class="model-actions"><div><b>A plan, not a promise.</b><p id="model-description"></p></div><button id="export-open" class="primary">Export build <span>↗</span></button></div>
<section class="details-panel"><div class="detail-tabs" role="tablist" aria-label="Model details"><button id="assembly-tab" role="tab" aria-selected="true" aria-controls="assembly-panel">Assembly <span id="step-pill"></span></button><button id="inventory-tab" role="tab" aria-selected="false" tabindex="-1" aria-controls="inventory-panel">Parts inventory</button><button id="checks-tab" role="tab" aria-selected="false" tabindex="-1" aria-controls="checks-panel">Checks <span id="checks-dot"></span></button></div>
<div id="assembly-panel" role="tabpanel" aria-labelledby="assembly-tab"><div class="step-heading"><div><span class="eyebrow">ONE LAYER AT A TIME</span><h3 id="step-title"></h3></div><button id="instructions" class="secondary">Printable notebook ↗</button></div><div class="step-controls"><button id="previous" class="square" aria-label="Previous assembly step">←</button><input id="step" type="range" min="0" value="0" aria-label="Assembly step"><button id="next" class="square" aria-label="Next assembly step">→</button><button id="all-steps" class="text-link">Show all</button></div><div class="step-layout"><div id="layer-map" class="layer-map"></div><div><p id="step-summary" class="hint"></p><div id="step-parts" class="step-parts"></div><p class="hint">Coordinates are grid boundaries. Bottom height is in plate units. Gray = earlier pieces. Full placements are in the printable notebook.</p></div></div></div>
<div id="inventory-panel" role="tabpanel" aria-labelledby="inventory-tab" hidden><div class="step-heading"><div><span class="eyebrow">THE SHOPPING LIST, MINUS THE SHOP</span><h3>Every piece accounted for.</h3></div><button id="csv-inline" class="secondary">Download CSV ↓</button></div><p class="hint">Documented common part IDs. Color codes are LDraw codes, not vendor SKUs. Part/color availability and prices have not been checked.</p><div class="table-scroll"><table><thead><tr><th>Part</th><th>Color</th><th class="numeric">Qty</th></tr></thead><tbody id="inventory-body"></tbody></table></div></div>
<div id="checks-panel" role="tabpanel" aria-labelledby="checks-tab" hidden><div class="step-heading"><div><span class="eyebrow">TRUST, BUT INSPECT</span><h3>Geometry checks, not a certification.</h3></div></div><div id="checks-grid" class="checks-grid"></div><div id="check-details"></div><p class="notice">Checks cover axis-aligned brick bodies and vertical stud-grid contacts only. Side-by-side touching does not connect pieces. Partial support can be a valid overhang or an unstable one. These checks do not simulate clutch, gravity, load, torque, tolerances, assembly access or real-world strength. Models are not physically verified.</p></div></section>
<footer>Made of possibilities. And ordinary bricks.<span>Independent prototype · Not affiliated with the LEGO Group.</span></footer></section></main>
<dialog id="export-dialog"><div class="dialog-heading"><div><p class="eyebrow">TAKE IT OFF THE WORKBENCH</p><h2>Keep every piece.</h2></div><button class="close" data-close="export-dialog" aria-label="Close export dialog">×</button></div><p class="hint">Exports always include the entire model, even when viewing one assembly step.</p><div class="export-grid"><button id="download-ldr"><b>LDraw model <span>.ldr ↗</span></b><small>Real part references, transforms & assembly steps.<br>Requires a standard LDraw parts library.</small></button><button id="download-csv"><b>Parts inventory <span>.csv ↓</span></b><small>Part ID, LDraw color and exact quantity.<br>No availability or price assumptions.</small></button><button id="download-json"><b>Editable brick plan <span>.json ↓</span></b><small>Import it again, edit it yourself or give it to an agent.</small></button><button id="download-html"><b>Assembly notebook <span>.html ↓</span></b><small>Offline layer maps, placements and inventory.<br>Open in a browser to print / save as PDF.</small></button><button id="download-png"><b>Current 3D view <span>.png ↓</span></b><small>A snapshot of the current camera and step.</small></button></div><p class="notice">Digital geometry only. Inspect the plan and prototype connections before buying or building.</p></dialog>
<dialog id="custom-dialog"><div class="dialog-heading"><div><p class="eyebrow">YOUR PLAN. YOUR RULES.</p><h2>Bring your own bricks.</h2></div><button class="close" data-close="custom-dialog" aria-label="Close custom plan dialog">×</button></div><p class="hint">Paste a version 1 plan or choose a JSON file (≤2 MB). Coordinates: x/z in studs, y in plates upward. Upright parts only, rotation 0 or 90. Current piece budget applies. Geometry issues are reported, not silently repaired.</p><label for="json-file" class="secondary file-button">Choose JSON file<input id="json-file" type="file" accept=".json,application/json"></label><label class="field-label" for="json-text">Brick plan JSON</label><textarea id="json-text" class="code-input" rows="10" spellcheck="false"></textarea><p class="hint">Supported parts: <span id="supported-parts"></span>. Supported colors: ${Object.keys(COLOR_BY_CODE).join(', ')}. See README for the complete schema.</p><p id="json-status" class="status" role="alert"></p><button id="import-json" class="primary">Load brick plan →</button></dialog>
<dialog id="guide-dialog"><div class="dialog-heading"><h2>Small vocabulary.<br>Real models.</h2><button class="close" data-close="guide-dialog" aria-label="Close prompt guide">×</button></div><p>Supported families: <b>cottage</b> (house / cabin), <b>tower</b>, <b>pyramid</b>.</p><ul><li>One body color: black, blue, green, red, yellow, white, tan, orange, brown, gray / grey.</li><li>Cottages can also have a second color followed by “roof”.</li><li>“size 16”, “16 studs wide”, “height 8”, “8 courses tall”.</li><li>“small” = 12 studs; “large” = 24; “short” = 4 courses; “tall” = 12.</li></ul><p class="notice">This is a deterministic grammar, not an AI model. Other objects and extra details are rejected. A prompt’s explicit dimensions override the sliders. Selected palettes quantize requested colors to their nearest available color.</p><p>Example: <code>a blue cottage with a red roof size 16 height 6</code></p></dialog>`;

let mode:'text'|'image'='text';
let plan:Plan=procedural('A tan cottage with a red roof',DEFAULTS);
let step=0;
let sourceImage:ImageBitmap|undefined;
let imageRequest=0;
let viewer:BrickViewer|undefined;
try {viewer=new BrickViewer($('viewer')); viewer.onSelect=b=>{$('selection').hidden=false;$('selection').textContent=`${b.id} · ${PART_BY_ID[b.part].name} · ${COLOR_BY_CODE[b.color].name} · (${b.x}, ${b.y}, ${b.z})`;};}
catch { $('webgl-error').hidden=false; $('webgl-error').textContent='3D preview unavailable: this browser could not create a WebGL context. Assembly maps, model generation and all data exports still work.'; ['fit','top','explode','spin','download-png'].forEach(id=>$(id).setAttribute('disabled','')); }
const options=():Options=>({size:Number($<HTMLInputElement>('size').value),height:Number($<HTMLInputElement>('height').value),budget:Number($<HTMLInputElement>('budget').value),palette:$<HTMLSelectElement>('palette').value});
function status(message:string,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
function slug(){return plan.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'bricksmith';}
function download(content:string,extension:string,mime:string){const url=URL.createObjectURL(new Blob([content],{type:mime}));const a=document.createElement('a');a.href=url;a.download=`${slug()}.${extension}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
function syncSettings(){ $('size-value').textContent=$<HTMLInputElement>('size').value;$('height-value').textContent=$<HTMLInputElement>('height').value;$('palette-swatches').innerHTML=PALETTES[options().palette].map(code=>`<span style="background:${COLOR_BY_CODE[code].hex}" title="${COLOR_BY_CODE[code].name} (${code})"></span>`).join(''); }
function setInputMode(value:'text'|'image'){mode=value;for(const m of ['text','image']){$(`${m}-tab`).setAttribute('aria-selected',String(m===mode));$(`${m}-tab`).tabIndex=m===mode?0:-1;$(`${m}-panel`).hidden=m!==mode;}const height=$<HTMLInputElement>('height');height.max=mode==='text'?'20':'8';height.value=String(Math.min(Number(height.value),Number(height.max)));$('height-unit').textContent=mode==='text'?'courses':'plates';$('height-hint').textContent=mode==='text'?'Body courses; base and cottage roof are additional.':'Relief: 3–8 color plates + 2 backing layers. Flat mosaic ignores height.';syncSettings();status('Settings changed. Build to apply them.');}
function connectTabs(ids:string[],select:(id:string)=>void){ids.forEach((id,i)=>$(id).addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?ids.length-1:(i+(e.key==='ArrowRight'?1:-1)+ids.length)%ids.length;select(ids[next]);$(ids[next]).focus();}));}
$('text-tab').onclick=()=>setInputMode('text');$('image-tab').onclick=()=>setInputMode('image');connectTabs(['text-tab','image-tab'],id=>setInputMode(id==='text-tab'?'text':'image'));
function selectDetails(id:string){for(const tab of ['assembly','inventory','checks']){const active=id===`${tab}-tab`;$(`${tab}-tab`).setAttribute('aria-selected',String(active));$(`${tab}-tab`).tabIndex=active?0:-1;$(`${tab}-panel`).hidden=!active;}}
for(const tab of ['assembly','inventory','checks'])$(`${tab}-tab`).onclick=()=>selectDetails(`${tab}-tab`);connectTabs(['assembly-tab','inventory-tab','checks-tab'],selectDetails);
for(const id of ['size','height','palette','budget'])$(id).addEventListener('input',()=>{syncSettings();status('Settings changed. Build to apply them.');});
$('prompt').addEventListener('input',()=>status('Prompt changed. Build to apply it.'));
document.querySelectorAll<HTMLButtonElement>('[data-prompt]').forEach(b=>b.onclick=()=>{setInputMode('text');$<HTMLTextAreaElement>('prompt').value=b.dataset.prompt!;build();});
function renderStep(){const ys=layers(plan);step=Math.min(Math.max(step,0),ys.length-1);const y=ys[step],newBricks=ordered(plan).filter(b=>b.y===y);$<HTMLInputElement>('step').max=String(ys.length-1);$<HTMLInputElement>('step').value=String(step);$('step-title').textContent=`Step ${step+1} of ${ys.length} · ${newBricks.length} new pieces`;$('step-summary').textContent=`Bottom elevation: ${y} plates (${(y*3.2).toFixed(1)} mm nominal). ${plan.bricks.filter(b=>b.y<=y).length} pieces assembled.`;$('layer-map').innerHTML=layerSVG(plan,step);$('step-parts').innerHTML=inventory({...plan,bricks:newBricks}).map(r=>`<div><span class="swatch" style="background:${COLOR_BY_CODE[r.color].hex}"></span><span>${esc(r.name)}<small>${r.part} · ${r.colorName}</small></span><b>×${r.quantity}</b></div>`).join('');$<HTMLButtonElement>('previous').disabled=step===0;$<HTMLButtonElement>('next').disabled=step===ys.length-1;$('visible-count').textContent=String(plan.bricks.filter(b=>b.y<=y).length);$('selection').hidden=true;if(viewer){viewer.step=step;viewer.rebuild();}}
function loadPlan(next:Plan){plan=next;const box=bounds(plan),ys=layers(plan),rows=inventory(plan),d=diagnose(plan);step=ys.length-1;$('model-name').textContent=plan.name;$('source-tag').textContent=plan.source==='relief'?'BRIGHTNESS HEIGHTMAP':plan.source==='mosaic'?'QUANTIZED MOSAIC':plan.source.toUpperCase();$('piece-count').textContent=plan.bricks.length.toLocaleString();$('color-count').textContent=String(new Set(plan.bricks.map(b=>b.color)).size);$('footprint').textContent=`${box.maxX-box.minX} × ${box.maxZ-box.minZ}`;$('step-count').textContent=String(ys.length);$('step-pill').textContent=String(ys.length);$('model-description').textContent=plan.description;$('inventory-body').innerHTML=rows.map(r=>`<tr><td><b>${r.name}</b><small>${r.part}.dat</small></td><td><span class="swatch" style="background:${COLOR_BY_CODE[r.color].hex}"></span>${r.colorName}<small>LDraw ${r.color}</small></td><td class="numeric">${r.quantity}</td></tr>`).join('');$('checks-grid').innerHTML=[[d.collisions.length,'Body overlaps'],[d.unsupported.length,'Without lower contact'],[d.partialSupport.length,'Partially supported'],[d.components.length,'Connected groups']].map(([n,label])=>`<div><strong>${n}</strong><span>${label}</span></div>`).join('');const warning=!!(d.collisions.length||d.unsupported.length||d.partialSupport.length||d.components.length>1||d.truncated);$('checks-dot').textContent=warning?'!':'·';$('checks-dot').className=warning?'warning':'ok';$('check-details').innerHTML=`<p class="hint">${d.groundCount} pieces start on the ground. ${d.connections} vertical contact pairs found.${d.truncated?' Diagnostic safety limit reached; lists and group counts are incomplete. Inspect a smaller plan.':''}</p>`+ (warning?`<details><summary>Inspect diagnostic piece IDs</summary><p>Overlaps: ${esc(d.collisions.slice(0,40).map(pair=>pair.join(' ↔ ')).join(', ')||'none')}</p><p>No lower contact: ${esc(d.unsupported.slice(0,40).join(', ')||'none')}</p><p>Partial support: ${esc(d.partialSupport.slice(0,40).join(', ')||'none')}</p><p>Groups: ${esc(d.components.slice(0,20).map(g=>`${g[0]} (${g.length} pieces)`).join('; '))}</p><p class="hint">Lists capped to 40 IDs / 20 groups in this summary.</p></details>`:'');viewer?.setPlan(plan);$('explode').setAttribute('aria-pressed','false');renderStep();document.documentElement.dataset.ready='true';}
function build(){try {const opts=options();let next:Plan;if(mode==='text'){const parsed=parsePrompt($<HTMLTextAreaElement>('prompt').value,opts);next=procedural($<HTMLTextAreaElement>('prompt').value,opts);$<HTMLInputElement>('size').value=String(parsed.size);$<HTMLInputElement>('height').value=String(parsed.height);syncSettings();}else{if(!sourceImage)throw Error('Choose an image first. It stays in your browser.');const ratio=sourceImage.width/sourceImage.height;const w=ratio>=1?opts.size:Math.max(1,Math.round(opts.size*ratio)),h=ratio>=1?Math.max(1,Math.round(opts.size/ratio)):opts.size;const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const context=canvas.getContext('2d',{willReadFrequently:true})!;context.drawImage(sourceImage,0,0,w,h);const imageMode=document.querySelector<HTMLInputElement>('input[name="image-mode"]:checked')!.value as 'mosaic'|'relief';next=imagePlan(context.getImageData(0,0,w,h).data,w,h,imageMode,opts);}loadPlan(next);status(`${next.bricks.length} pieces. Entire model generated locally.`);}catch(e){status((e as Error).message,true);}}
$('generate').onclick=build;
async function acceptImage(file:File){const request=++imageRequest;try {if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('Please choose a PNG, JPEG or WebP image.');if(file.size>20*1024*1024)throw Error('Image is larger than 20 MB. Resize it before importing.');status('Reading image locally…');const bitmap=await createImageBitmap(file);if(request!==imageRequest){bitmap.close();return;}if(bitmap.width*bitmap.height>40000000){bitmap.close();throw Error('Image exceeds 40 megapixels. Resize it first.');}sourceImage?.close();sourceImage=bitmap;const preview=document.createElement('canvas');const scale=Math.min(1,300/bitmap.width,180/bitmap.height);preview.width=Math.round(bitmap.width*scale);preview.height=Math.round(bitmap.height*scale);preview.getContext('2d')!.drawImage(bitmap,0,0,preview.width,preview.height);$<HTMLImageElement>('image-preview').src=preview.toDataURL('image/png');$('image-preview').hidden=false;$('upload-label').innerHTML='<b>Change image</b><small>Read locally · never uploaded</small>';setInputMode('image');build();}catch(e){if(request===imageRequest)status((e as Error).message,true);}}
$<HTMLInputElement>('image-file').onchange=e=>{const file=(e.target as HTMLInputElement).files?.[0];if(file)void acceptImage(file);};
$('drop-zone').addEventListener('dragover',e=>{e.preventDefault();$('drop-zone').classList.add('dragging');});$('drop-zone').addEventListener('dragleave',()=>$('drop-zone').classList.remove('dragging'));$('drop-zone').addEventListener('drop',e=>{e.preventDefault();$('drop-zone').classList.remove('dragging');const file=e.dataTransfer?.files[0];if(file)void acceptImage(file);});
document.querySelectorAll('input[name="image-mode"]').forEach(el=>el.addEventListener('change',()=>status('Image mode changed. Build to apply it.')));
$('step').oninput=()=>{step=Number($<HTMLInputElement>('step').value);renderStep();};$('previous').onclick=()=>{step--;renderStep();};$('next').onclick=()=>{step++;renderStep();};$('all-steps').onclick=()=>{step=layers(plan).length-1;renderStep();};$('fit').onclick=()=>viewer?.fit();$('top').onclick=()=>viewer?.fit(true);$('explode').onclick=()=>{if(!viewer)return;viewer.exploded=!viewer.exploded;$('explode').setAttribute('aria-pressed',String(viewer.exploded));viewer.rebuild();};$('spin').onclick=()=>{if(!viewer)return;viewer.spin=!viewer.spin;$('spin').setAttribute('aria-pressed',String(viewer.spin));};
for(const [button,dialog] of [['export-open','export-dialog'],['custom-open','custom-dialog'],['syntax','guide-dialog']])$(button).onclick=()=>$<HTMLDialogElement>(dialog).showModal();
document.querySelectorAll<HTMLButtonElement>('[data-close]').forEach(b=>b.onclick=()=>$<HTMLDialogElement>(b.dataset.close!).close());
$('download-ldr').onclick=()=>download(toLDraw(plan),'ldr','text/plain;charset=utf-8');$('download-csv').onclick=$('csv-inline').onclick=()=>download(toCSV(plan),'csv','text/csv;charset=utf-8');$('download-json').onclick=()=>download(toJSON(plan),'json','application/json');$('download-html').onclick=()=>download(instructionHTML(plan),'html','text/html;charset=utf-8');$('download-png').onclick=()=>{if(!viewer)return;const a=document.createElement('a');a.href=viewer.screenshot();a.download=`${slug()}-view.png`;a.click();};
$('instructions').onclick=()=>{const url=URL.createObjectURL(new Blob([instructionHTML(plan)],{type:'text/html'}));const tab=window.open(url,'_blank');if(tab)tab.opener=null;else status('The notebook tab was blocked. Allow pop-ups or download its HTML from Export build.',true);setTimeout(()=>URL.revokeObjectURL(url),60000);};
$('supported-parts').textContent=Object.keys(PART_BY_ID).join(', ');
$<HTMLTextAreaElement>('json-text').value=toJSON({version:1,name:'Two-piece starter',source:'custom',description:'A 2 × 4 brick with one 2 × 2 brick on top.',bricks:[{id:'base',part:'3001',color:4,x:0,y:0,z:0,rotation:0},{id:'top',part:'3003',color:14,x:1,y:3,z:0,rotation:0}]});
$<HTMLInputElement>('json-file').onchange=async e=>{const file=(e.target as HTMLInputElement).files?.[0];if(!file)return;try{if(file.size>2*1024*1024)throw Error('JSON file exceeds 2 MB.');$<HTMLTextAreaElement>('json-text').value=await file.text();$('json-status').textContent='File read locally. Select Load brick plan to validate.';}catch(error){$('json-status').textContent=(error as Error).message;}};
$('import-json').onclick=()=>{try{const text=$<HTMLTextAreaElement>('json-text').value;if(text.length>2*1024*1024)throw Error('JSON text exceeds 2 MB.');const budget=options().budget;if(!Number.isInteger(budget)||budget<20||budget>5000)throw Error('Piece budget must be an integer from 20 to 5,000.');const next=enforceBudget(validatePlan(JSON.parse(text)),budget);loadPlan(next);$<HTMLDialogElement>('custom-dialog').close();status('Custom plan loaded. Review the Checks tab before building.');}catch(e){$('json-status').textContent=(e as Error).message;}};
syncSettings();loadPlan(plan);
