import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {bounds,dimensions,COLOR_BY_CODE,layers,type Plan,type Brick} from './model';
export class BrickViewer {
  renderer:THREE.WebGLRenderer;scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(38,1,.1,5000);controls:OrbitControls;
  group=new THREE.Group(); ground:THREE.Mesh; grid:THREE.GridHelper; bodies?:THREE.InstancedMesh; studs?:THREE.InstancedMesh;
  visible:Brick[]=[];plan?:Plan;step=Infinity;exploded=false;spin=false;frame=0;resize:ResizeObserver;selection=new THREE.Box3Helper(new THREE.Box3(),0xe76b38);onSelect?:(b:Brick)=>void;
  constructor(public container:HTMLElement) {
    this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.setClearColor(0xe9eee8,0);this.renderer.domElement.setAttribute('aria-label','Interactive 3D brick model. Drag to orbit, scroll to zoom, right-drag to pan.');this.renderer.domElement.setAttribute('role','img');this.renderer.domElement.tabIndex=0;container.append(this.renderer.domElement);
    this.camera.position.set(28,25,32);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.minDistance=3;this.controls.maxDistance=2500;this.controls.maxPolarAngle=Math.PI*.49;
    this.scene.add(new THREE.HemisphereLight(0xffffff,0x83917e,3));const key=new THREE.DirectionalLight(0xffeedc,4);key.position.set(-18,35,20);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-60,right:60,top:60,bottom:-60,near:1,far:150});key.shadow.bias=-.0003;key.shadow.normalBias=.035;this.scene.add(key);const fill=new THREE.DirectionalLight(0xffffff,1.8);fill.position.set(20,15,-25);this.scene.add(fill);
    this.ground=new THREE.Mesh(new THREE.PlaneGeometry(600,600),new THREE.ShadowMaterial({color:0x304133,opacity:.16}));this.ground.rotation.x=-Math.PI/2;this.ground.position.y=-.025;this.ground.receiveShadow=true;this.scene.add(this.ground);
    this.grid=new THREE.GridHelper(120,120,0xbac6b7,0xd4ddd1);this.grid.position.y=-.03;const gm=this.grid.material as THREE.Material;gm.transparent=true;gm.opacity=.24;this.scene.add(this.grid,this.group,this.selection);this.selection.visible=false;
    this.resize=new ResizeObserver(()=>{const {width,height}=container.getBoundingClientRect();if(!width||!height)return;this.renderer.setSize(width,height);this.camera.aspect=width/height;this.camera.updateProjectionMatrix();});this.resize.observe(container);
    let down=[0,0];this.renderer.domElement.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY];});this.renderer.domElement.addEventListener('pointerup',e=>{if(Math.hypot(e.clientX-down[0],e.clientY-down[1])<4)this.pick(e);});
    this.renderer.domElement.addEventListener('keydown',e=>{if(e.key==='Home'){this.fit();e.preventDefault();}if(e.key==='+'||e.key==='='){this.camera.position.sub(this.controls.target).multiplyScalar(.9).add(this.controls.target);e.preventDefault();}if(e.key==='-'){this.camera.position.sub(this.controls.target).multiplyScalar(1.1).add(this.controls.target);e.preventDefault();}});
    const animate=()=>{this.frame=requestAnimationFrame(animate);this.controls.autoRotate=this.spin;this.controls.autoRotateSpeed=.7;this.controls.update();this.renderer.render(this.scene,this.camera);};animate();
  }
  setPlan(plan:Plan){this.plan=plan;this.step=layers(plan).length-1;this.exploded=false;this.rebuild();this.fit();}
  rebuild(){if(!this.plan)return;for(const obj of [...this.group.children]){this.group.remove(obj);if(obj instanceof THREE.InstancedMesh){obj.geometry.dispose();(obj.material as THREE.Material).dispose();obj.dispose();}}this.selection.visible=false;
    const levels=layers(this.plan),maxY=levels[Math.min(this.step,levels.length-1)];this.visible=this.plan.bricks.filter(b=>b.y<=maxY);
    const studCount=this.visible.reduce((n,b)=>{const d=dimensions(b);return n+d.w*d.d;},0);
    this.bodies=new THREE.InstancedMesh(new RoundedBoxGeometry(1,1,1,2,.035),new THREE.MeshStandardMaterial({roughness:.32,metalness:0}),this.visible.length);
    this.studs=new THREE.InstancedMesh(new THREE.CylinderGeometry(.3,.3,.18,16),new THREE.MeshStandardMaterial({roughness:.32,metalness:0}),studCount);
    const matrix=new THREE.Matrix4(),q=new THREE.Quaternion(),pos=new THREE.Vector3(),scale=new THREE.Vector3(),color=new THREE.Color();let si=0;
    for(let i=0;i<this.visible.length;i++){const b=this.visible[i],{w,d,h}=dimensions(b),extra=this.exploded?levels.indexOf(b.y)*.7:0;const y=b.y*.4+extra;
      color.set(COLOR_BY_CODE[b.color].hex);if(b.y<maxY&&this.step<levels.length-1)color.lerp(new THREE.Color('#bcc7b8'),.2);
      pos.set(b.x+w/2,y+h*.2,(b.z+d/2));scale.set(w-.018,h*.4-.018,d-.018);matrix.compose(pos,q,scale);this.bodies.setMatrixAt(i,matrix);this.bodies.setColorAt(i,color);
      for(let x=0;x<w;x++)for(let z=0;z<d;z++){pos.set(b.x+x+.5,y+h*.4+.08,(b.z+z+.5));matrix.compose(pos,q,new THREE.Vector3(1,1,1));this.studs.setMatrixAt(si,matrix);this.studs.setColorAt(si,color);si++;}
    }
    this.bodies.instanceMatrix.needsUpdate=true;this.studs.instanceMatrix.needsUpdate=true;if(this.bodies.instanceColor)this.bodies.instanceColor.needsUpdate=true;if(this.studs.instanceColor)this.studs.instanceColor.needsUpdate=true;
    this.bodies.castShadow=this.bodies.receiveShadow=true;this.studs.castShadow=this.studs.receiveShadow=true;this.group.add(this.bodies,this.studs);this.renderer.domElement.dataset.bricks=String(this.visible.length);this.renderer.domElement.dataset.studs=String(studCount);
  }
  fit(top=false){if(!this.plan)return;const damping=this.controls.enableDamping;this.controls.enableDamping=false;this.controls.update();const rect=this.container.getBoundingClientRect();if(rect.width&&rect.height){this.camera.aspect=rect.width/rect.height;this.camera.updateProjectionMatrix();}const b=bounds(this.plan),maxY=b.maxY*.4+.2+(this.exploded?(layers(this.plan).length-1)*.7:0),center=new THREE.Vector3((b.minX+b.maxX)/2,maxY/2,(b.minZ+b.maxZ)/2),direction=(top?new THREE.Vector3(0,1,.0001):new THREE.Vector3(-.8,.85,-1)).normalize(),right=new THREE.Vector3().crossVectors(new THREE.Vector3(0,1,0),direction).normalize(),up=new THREE.Vector3().crossVectors(direction,right),tanV=Math.tan(THREE.MathUtils.degToRad(this.camera.fov/2)),tanH=tanV*this.camera.aspect;let distance=4;const elevations=layers(this.plan);for(const brick of this.plan.bricks){const d=dimensions(brick),extra=this.exploded?elevations.indexOf(brick.y)*.7:0;for(const x of [brick.x,brick.x+d.w])for(const y of [brick.y*.4+extra,(brick.y+d.h)*.4+extra+.2])for(const z of [brick.z,brick.z+d.d]){const delta=new THREE.Vector3(x,y,z).sub(center);distance=Math.max(distance,delta.dot(direction)+(top?1.25:1.16)*Math.max(Math.abs(delta.dot(right))/tanH,Math.abs(delta.dot(up))/tanV));}}this.controls.target.copy(center);this.camera.position.copy(center).add(direction.multiplyScalar(distance));this.controls.update();this.controls.enableDamping=damping;}
  pick(e:PointerEvent){if(!this.bodies)return;const rect=this.renderer.domElement.getBoundingClientRect();const pointer=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(pointer,this.camera);const hit=ray.intersectObject(this.bodies)[0];if(hit?.instanceId===undefined){this.selection.visible=false;return;}const b=this.visible[hit.instanceId],{w,d,h}=dimensions(b),extra=this.exploded&&this.plan?layers(this.plan).indexOf(b.y)*.7:0;this.selection.box.set(new THREE.Vector3(b.x,b.y*.4+extra,b.z),new THREE.Vector3(b.x+w,(b.y+h)*.4+extra+.18,b.z+d));this.selection.visible=true;this.onSelect?.(b);}
  screenshot(){this.renderer.render(this.scene,this.camera);return this.renderer.domElement.toDataURL('image/png');}
  dispose(){cancelAnimationFrame(this.frame);this.resize.disconnect();this.controls.dispose();this.renderer.dispose();}
}
