import {readdirSync,readFileSync,writeFileSync,lstatSync,realpathSync,existsSync,mkdirSync,renameSync} from 'node:fs';
import {mkdir,mkdtemp,rm,rename,open} from 'node:fs/promises';
import {resolve,join,dirname,relative} from 'node:path';
import {homedir} from 'node:os';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
export const SOURCE='https://library.ldraw.org/library/updates/complete.zip';
export const DEFAULT_LIBRARY=join(homedir(),'.cache','bricksmith','ldraw-official');
export class CatalogError extends Error {constructor(code,message,details={}){super(message);this.code=code;this.details=details;this.exitCode=2;}}
export const fail=(code,message,details)=>{throw new CatalogError(code,message,details);};
export const sha256=b=>createHash('sha256').update(b).digest('hex');
export function safeRef(value){if(typeof value!=='string'||value.length>240||!value||/[\x00-\x20:%?]/.test(value))fail('UNSAFE_REFERENCE','Invalid LDraw reference',{value});const ref=value.replaceAll('\\','/').toLowerCase();if(ref.startsWith('/')||ref.split('/').some(p=>!p||p==='.'||p==='..')||!/^[a-z0-9_+#.,/\-]+$/.test(ref))fail('UNSAFE_REFERENCE','Unsafe library path',{value});return ref;}
export function mainId(value){const ref=safeRef(value);const id=ref.endsWith('.dat')?ref.slice(0,-4):ref;if(id.includes('/')||!id)fail('PART_ID','Select a main catalog ID, not a subpart path',{value});return id;}
export function atomicJSON(path,value){mkdirSync(dirname(path),{recursive:true});const temp=path+`.${process.pid}.tmp`;writeFileSync(temp,JSON.stringify(value,null,2)+'\n',{flag:'wx'});renameSync(temp,path);}
function walk(root,dir='',acc=[]){for(const entry of readdirSync(join(root,dir),{withFileTypes:true}).sort((a,b)=>a.name<b.name?-1:1)){if(entry.name.startsWith('.bricksmith-'))continue;const path=join(dir,entry.name);const st=lstatSync(join(root,path));if(st.isSymbolicLink()||(!st.isFile()&&!st.isDirectory()))fail('LIBRARY_LINK','Library must contain only regular files/directories',{path});if(st.isDirectory())walk(root,path,acc);else {if(st.size>64_000_000||acc.length>=100000)fail('LIBRARY_BUDGET','Library resource limit exceeded');acc.push(path);}}return acc;}
export function metadata(text,path){const lines=text.split(/\r?\n/);const name=(lines.find(l=>/^0\s+\S/.test(l))??'0').replace(/^0\s*/,'');const org=lines.find(l=>/^0\s+!LDRAW_ORG\s/.test(l))?.replace(/^0\s+!LDRAW_ORG\s+/,'')??'';const category=lines.find(l=>/^0\s+!CATEGORY\s/.test(l))?.replace(/^0\s+!CATEGORY\s+/,'')??name.replace(/^[~_=]+/,'').trim().split(/\s+/)[0];const main=/^parts\/[^/]+\.dat$/.test(path);return {id:main?path.slice(6,-4):path,path,name,category,org,kind:main?'main':path.startsWith('parts/s/')?'subpart':path.startsWith('p/')?'primitive':'other',alias:/Alias/.test(org)||/^=/.test(name),moved:/~Moved to/i.test(name),patterned:/\bPattern\b/i.test(name),author:lines.find(l=>/^0\s+Author:/.test(l))?.replace(/^0\s+Author:\s*/,''),license:lines.find(l=>/^0\s+!LICENSE/.test(l))?.replace(/^0\s+!LICENSE\s*/,''),keywords:lines.filter(l=>/^0\s+!KEYWORDS/.test(l)).map(l=>l.replace(/^0\s+!KEYWORDS\s*/,'')).join(', '),texmap:lines.some(l=>/^0\s+!TEXMAP/.test(l))};}
export function parseColors(text){return text.split(/\r?\n/).filter(l=>/^0\s+!COLOUR\s/.test(l)).map(line=>{const m=line.match(/^0\s+!COLOUR\s+(\S+)\s+CODE\s+(\d+)\s+VALUE\s+(#[\da-f]+)\s+EDGE\s+(\S+)/i);if(!m)fail('COLOR_CONFIG','Malformed LDConfig color',{line});return {code:Number(m[2]),name:m[1],value:m[3],edge:m[4],alpha:Number(line.match(/\bALPHA\s+(\d+)/)?.[1]??255),luminance:Number(line.match(/\bLUMINANCE\s+(\d+)/)?.[1]??0),definition:line};});}
export function indexLibrary(directory=DEFAULT_LIBRARY,provenance){const root=realpathSync(resolve(directory));if(!existsSync(join(root,'parts'))||!existsSync(join(root,'p')))fail('LIBRARY_LAYOUT','Expected extracted LDraw root containing parts/ and p/');const files={};const parts=[];let bytes=0;for(const path of walk(root)){const key=safeRef(path);if(files[key])fail('CASE_COLLISION','Case-insensitive duplicate',{path});const b=readFileSync(join(root,path));bytes+=b.length;if(bytes>2_000_000_000)fail('LIBRARY_BUDGET','Expanded library exceeds 2 GB');files[key]={path,bytes:b.length,sha256:sha256(b)};if(key.endsWith('.dat'))parts.push(metadata(b.toString('utf8'),key));}
 if(!files['ldconfig.ldr'])fail('COLOR_CONFIG','LDConfig.ldr missing');const config=readFileSync(join(root,files['ldconfig.ldr'].path),'utf8');const colors=parseColors(config);const colorConfigVersion=config.match(/UPDATE\s+(\S+)/)?.[1]??'unknown';const version=parts.map(p=>p.org.match(/UPDATE\s+(\d{4}-\d{2})/)?.[1]).filter(Boolean).sort().at(-1)??'unknown';
 const counts={files:Object.keys(files).length,datFiles:parts.length,mainParts:parts.filter(p=>p.kind==='main').length,subparts:parts.filter(p=>p.kind==='subpart').length,primitives:parts.filter(p=>p.kind==='primitive').length,otherDat:parts.filter(p=>p.kind==='other').length,mainAliases:parts.filter(p=>p.kind==='main'&&p.alias).length,mainMoved:parts.filter(p=>p.kind==='main'&&p.moved).length,mainShortcuts:parts.filter(p=>p.kind==='main'&&/^(Unofficial_)?Shortcut\b/.test(p.org)).length,mainPatterns:parts.filter(p=>p.kind==='main'&&p.patterned).length,colors:colors.length,textures:Object.keys(files).filter(p=>/\.(png|jpg|jpeg)$/.test(p)).length};
 const treeDigest=sha256(Object.entries(files).map(([k,f])=>`${k}\0${f.sha256}\n`).join(''));const old=existsSync(join(root,'.bricksmith-provenance.json'))?JSON.parse(readFileSync(join(root,'.bricksmith-provenance.json'),'utf8')):null;
 const manifest={schema:'bricksmith.library.v1',version,versionMethod:'maximum official !LDRAW_ORG UPDATE across indexed .dat headers',colorConfigVersion,source:provenance?.source??old?.source??'user-supplied directory (origin not authenticated)',archiveSha256:provenance?.archiveSha256??old?.archiveSha256??null,archiveBytes:provenance?.archiveBytes??old?.archiveBytes??null,treeDigest,expandedBytes:bytes,counts,countNotice:'Main files include aliases, moved entries, patterns and assemblies; not unique purchasable parts or complete LEGO-company inventory.',indexedAt:new Date().toISOString()};
 const index={manifest,files,parts,colors};atomicJSON(join(root,'.bricksmith-index.json'),index);atomicJSON(join(root,'.bricksmith-provenance.json'),manifest);return manifest;}
export class Library {
 constructor(directory=DEFAULT_LIBRARY){this.root=realpathSync(resolve(directory));const path=join(this.root,'.bricksmith-index.json');if(!existsSync(path))fail('INDEX_MISSING','Run library index --library DIR first');const idx=JSON.parse(readFileSync(path,'utf8'));if(idx.manifest?.schema!=='bricksmith.library.v1')fail('INDEX_VERSION','Unsupported index');Object.assign(this,idx);this.entries=new Map(this.parts.filter(p=>p.kind==='main').map(p=>[p.id,p]));this.textCache=new Map();this.geometryCache=new Map();}
 bytes(ref){ref=safeRef(ref);const f=this.files[ref];if(!f)fail('DEPENDENCY_MISSING','Missing catalog file',{reference:ref});const path=join(this.root,f.path);const canonical=realpathSync(path);if(!canonical.startsWith(this.root+'/'))fail('LIBRARY_ESCAPE','File escapes library root');let cur=this.root;for(const segment of relative(this.root,path).split('/')){cur=join(cur,segment);if(lstatSync(cur).isSymbolicLink())fail('LIBRARY_LINK','Library link rejected',{ref});}const st=lstatSync(path);if(!st.isFile()||st.size>64_000_000)fail('LIBRARY_BUDGET','Invalid library file');const bytes=readFileSync(path);if(sha256(bytes)!==f.sha256)fail('LIBRARY_CHANGED','Indexed file changed: re-index intentionally',{ref});return bytes;}
 text(ref){ref=safeRef(ref);if(!this.textCache.has(ref))this.textCache.set(ref,this.bytes(ref).toString('utf8'));return this.textCache.get(ref);}
 part(id){id=mainId(id);const part=this.entries.get(id);if(!part)fail('UNKNOWN_PART','Part not in indexed main catalog',{id});return part;}
 texture(ref,from=''){ref=safeRef(ref);const candidates=[ref,join(dirname(from),'textures',ref).replaceAll('\\','/'),'parts/textures/'+ref,'textures/'+ref];for(const c of candidates)if(this.files[c])return c;fail('TEXTURE_MISSING','TEXMAP texture absent',{ref,from});}
 resolve(ref,from=''){ref=safeRef(ref);const candidates=[ref,'parts/'+ref,'p/'+ref,join(dirname(from),ref).replaceAll('\\','/')];for(const c of candidates)if(Object.hasOwn(this.files,c))return c;fail('DEPENDENCY_MISSING','LDraw reference is absent from indexed library',{ref,from});}
 search({query='',category,offset=0,limit=30,kind='main'}={}){if(!Number.isInteger(offset)||offset<0||!Number.isInteger(limit)||limit<1||limit>200)fail('PAGINATION','offset >= 0 and limit 1–200 required');if(!['main','subpart','primitive','other','all'].includes(kind))fail('KIND','Invalid catalog kind');const terms=query.toLowerCase().split(/\s+/).filter(Boolean);const rows=this.parts.filter(p=>(kind==='all'||p.kind===kind)&&(!category||p.category.toLowerCase()===category.toLowerCase())&&terms.every(t=>`${p.id} ${p.name} ${p.category} ${p.keywords}`.toLowerCase().includes(t)));return {total:rows.length,offset,limit,nextOffset:offset+limit<rows.length?offset+limit:null,results:rows.slice(offset,offset+limit),library:this.manifest};}
 closure(ids){const visited=new Set(),active=new Set(),refs={};let total=0;const visit=(path,depth)=>{if(active.has(path))fail('DEPENDENCY_CYCLE','Cyclic LDraw dependency',{path});if(visited.has(path))return;if(depth>64||visited.size>10000)fail('DEPENDENCY_BUDGET','Dependency traversal budget');active.add(path);const text=this.text(path);total+=Buffer.byteLength(text);if(total>128_000_000)fail('DEPENDENCY_BUDGET','Selected source exceeds 128 MB');for(const line of text.split(/\r?\n/)){const t=line.trim().split(/\s+/);if(t[0]==='1'){if(t.length<15||t.slice(2,14).some(v=>!Number.isFinite(Number(v))))fail('LDRAW_SYNTAX','Invalid type 1 reference',{path,line});const ref=safeRef(t.slice(14).join(' '));const target=this.resolve(ref,path);if(refs[ref]&&refs[ref]!==target)fail('AMBIGUOUS_REFERENCE','Context-dependent reference not packable',{ref});refs[ref]=target;visit(target,depth+1);}if(/^0\s+!TEXMAP\s+(START|NEXT)/.test(line)){for(const texture of t.slice(13).filter(v=>/\.(png|jpe?g)$/i.test(v))){const target=this.texture(texture,path);this.bytes(target);visited.add(target);}}}active.delete(path);visited.add(path);};for(const id of ids)visit(this.part(id).path,0);return {files:[...visited].sort(),references:refs,sourceBytes:total};}
 geometry(id){const part=this.part(id);this.closure([id]);let work=0;const rec=(path,stack=[])=>{if(this.geometryCache.has(path))return this.geometryCache.get(path);if(stack.includes(path))fail('DEPENDENCY_CYCLE','Cycle',{path});let points=[],triangles=0,lines=0,conditionalLines=0;for(const line of this.text(path).split(/\r?\n/)){const t=line.trim().split(/\s+/);if(t[0]==='1'){const n=t.slice(2,14).map(Number),g=rec(this.resolve(t.slice(14).join(' '),path),[...stack,path]);triangles+=g.triangles;lines+=g.lines;conditionalLines+=g.conditionalLines;for(let i=0;i<g.points.length;i+=3){const [x,y,z]=g.points.slice(i,i+3);points.push(n[0]+n[3]*x+n[4]*y+n[5]*z,n[1]+n[6]*x+n[7]*y+n[8]*z,n[2]+n[9]*x+n[10]*y+n[11]*z);}}else if(t[0]==='3'||t[0]==='4'){const v=t.slice(2).map(Number);if(v.length!==(t[0]==='3'?9:12)||v.some(n=>!Number.isFinite(n)))fail('LDRAW_SYNTAX','Invalid polygon',{path});points.push(...v);triangles+=t[0]==='3'?1:2;}else if(t[0]==='2')lines++;else if(t[0]==='5')conditionalLines++;if(points.length>6_000_000)fail('GEOMETRY_BUDGET','Part polygon budget exceeded',{path});}work+=points.length;if(work>30_000_000)fail('GEOMETRY_BUDGET','Geometry traversal budget exceeded');const g={points:new Float64Array(points),triangles,lines,conditionalLines};this.geometryCache.set(path,g);return g;};return rec(part.path);}
 inspect(id){const part=this.part(id),closure=this.closure([id]),g=this.geometry(id);const min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<g.points.length;i++) {const axis=i%3;min[axis]=Math.min(min[axis],g.points[i]);max[axis]=Math.max(max[axis],g.points[i]);}if(!g.points.length)fail('EMPTY_GEOMETRY','Part has no polygon geometry',{id});return {...part,header:this.text(part.path).split(/\r?\n/).filter(l=>l.startsWith('0 ')).slice(0,80),bounds:{min,max,size:max.map((v,i)=>v-min[i]),units:'LDU',method:'actual recursively transformed type 3/4 polygon vertices; not a rectangular proxy'},geometry:{triangles:g.triangles,lines:g.lines,conditionalLines:g.conditionalLines},dependencies:closure,library:this.manifest,physicalConnections:'unverified'};}
}
export async function installLibrary({directory=DEFAULT_LIBRARY,archive,sha256:expected}={}){directory=resolve(directory);if(!expected&&!archive){const pin=join(import.meta.dirname,'official-library.lock.json');if(existsSync(pin))expected=JSON.parse(readFileSync(pin,'utf8')).archiveSha256;}if(existsSync(directory)){const lib=new Library(directory);if(expected&&lib.manifest.archiveSha256!==expected)fail('DIGEST_MISMATCH','Installed archive differs from requested digest');return {cached:true,library:directory,...lib.manifest};}await mkdir(dirname(directory),{recursive:true});const temporary=await mkdtemp(join(dirname(directory),'.bricksmith-install-'));try{let zip=archive?resolve(archive):join(temporary,'complete.zip');if(!archive){const res=await fetch(SOURCE,{signal:AbortSignal.timeout(1200000)});if(!res.ok)fail('DOWNLOAD',`Official archive HTTP ${res.status}`);const handle=await open(zip,'wx');let bytes=0;try{for await(const chunk of res.body){bytes+=chunk.length;if(bytes>512_000_000)fail('ARCHIVE_BUDGET','Download exceeds 512 MB');await handle.write(chunk);}}finally{await handle.close();}}if(lstatSync(zip).size>512_000_000)fail('ARCHIVE_BUDGET','Archive exceeds 512 MB');const data=readFileSync(zip),digest=sha256(data);if(expected&&digest!==expected)fail('DIGEST_MISMATCH','Archive SHA-256 mismatch',{expected,actual:digest});const extract=join(temporary,'extracted');const result=spawnSync('python3',[join(import.meta.dirname,'safe-extract.py'),zip,extract],{encoding:'utf8',timeout:180000});if(result.status!==0)fail('ARCHIVE_EXTRACT',result.stderr||result.error?.message||'Extraction failed');const root=existsSync(join(extract,'ldraw','parts'))?join(extract,'ldraw'):extract;const manifest=indexLibrary(root,{source:archive?'user-provided archive; digest identifies content':SOURCE,archiveSha256:digest,archiveBytes:data.length});await rename(root,directory);return {cached:false,library:directory,...manifest};}finally{await rm(temporary,{recursive:true,force:true});}}

// Whole installed catalog audit, reads each local definition once; no per-part network fetching.
export function auditLibrary(library){const missing=[],syntax=[],graph=new Map();let references=0,verifiedBytes=0;for(const [path,entry] of Object.entries(library.files)){const data=library.bytes(path);verifiedBytes+=data.length;if(!path.endsWith('.dat'))continue;const deps=[];for(const line of data.toString('utf8').split(/\r?\n/)){const t=line.trim().split(/\s+/);if(t[0]!=='1')continue;references++;try{if(t.length<15||t.slice(2,14).some(v=>!Number.isFinite(Number(v))))fail('LDRAW_SYNTAX','Bad transform');deps.push(library.resolve(t.slice(14).join(' '),path));}catch(e){const issue={file:path,line,code:e.code,message:e.message};if(e.code==='DEPENDENCY_MISSING')missing.push(issue);else syntax.push(issue);}}graph.set(path,deps);}const visited=new Set(),active=new Set(),cycles=[];const walk=path=>{if(active.has(path)){cycles.push(path);return;}if(visited.has(path))return;active.add(path);for(const child of graph.get(path)??[])walk(child);active.delete(path);visited.add(path);};for(const path of graph.keys())walk(path);return {ok:!missing.length&&!syntax.length&&!cycles.length,scope:'Every indexed file hash; all type-1 references and cycles. TEXMAP capability is separately gated at render.',verifiedFiles:Object.keys(library.files).length,verifiedBytes,definitions:graph.size,references,missing,syntax,cycles,library:library.manifest};}
